package net.citrite.pip.claim_validation_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SomeObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SomeObject() {
    }




}