package net.citrite.pip.claim_validation_poc;

import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import net.citrite.pip.canonical.bre.BREObjectSFDC;
import net.citrite.pip.bre.Validation;

function void registerValidation(BREObjectSFDC breObjectSFDC, String checkName, String checkType, String checkResult, Boolean header) {
        
        Validation validation = new Validation();
        validation.setCheckName(checkName);
        validation.setCheckType(checkType);
        validation.setCheckResult(checkResult);
        validation.setHeader(header);
        validation.setCheckDate(LocalDate.now());
        breObjectSFDC.getValidations().add(validation);
        
}