package net.citrite.pip.claim_validation_poc;

/*function void registerValidation(BREObjectSFDC breObjectSFDC, String orderID, String checkName, String checkType, String checkResult, Boolean header) {
        
        Validation validation = new Validation();
        validation.setOrderID(orderID);
        validation.setCheckName(checkName);
        validation.setCheckType(checkType);
        validation.setCheckResult(checkResult);
        validation.setHeader(header);
        validation.setCheckDate(LocalDate.now());
        breObjectSFDC.getValidations().add(validation);
}*/

function String hello(String name) {
	return "Hello "+name+"!";
}