serialver -classpath target/classes com.citrix.policy_poc.AuthorizationItem
serialver -classpath target/classes com.citrix.policy_poc.BREObjectSFDC
serialver -classpath target/classes com.citrix.policy_poc.EndUserInfo
serialver -classpath target/classes com.citrix.policy_poc.Info
serialver -classpath target/classes com.citrix.policy_poc.Order
serialver -classpath target/classes com.citrix.policy_poc.OrderHeader
serialver -classpath target/classes com.citrix.policy_poc.OrderLineItem
serialver -classpath target/classes com.citrix.policy_poc.OriginalOrder
serialver -classpath target/classes com.citrix.policy_poc.PartnerFunctions
serialver -classpath target/classes com.citrix.policy_poc.PartnerInfo
serialver -classpath target/classes com.citrix.policy_poc.Request
serialver -classpath target/classes com.citrix.policy_poc.RewardRegistration
serialver -classpath target/classes com.citrix.policy_poc.Specialization
serialver -classpath target/classes com.citrix.policy_poc.Tag
serialver -classpath target/classes com.citrix.policy_poc.Validation
